name: GitHub Actions Reusable workflow secrets Input Demo

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true  

jobs:
  Reusable-workflow-secrets-Input-Demo:
    runs-on: ubuntu-latest
    steps:
       - run: |
          echo "Hello" ${{ inputs.username }}
          echo "Hello" ${{ secrets.token }}   
    

  
